// CHECKING AUTH STATE
export const CHECKING_AUTH_STATE_BEGINS = "CHECKING_AUTH_STATE_BEGINS";
export const CHECKING_AUTH_STATE_SUCCESS = "CHECKING_AUTH_STATE_SUCCESS";
export const CHECKING_AUTH_STATE_FAILURE = "CHECKING_AUTH_STATE_FAILURE";
// SIGN IN
export const SIGNIN_BEGINS = "SIGNIN_BEGINS";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAILURE = "SIGNIN_FAILURE";
// SIGN OUT
export const SIGNOUT_BEGINS = "SIGNOUT_BEGINS";
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";
export const SIGNOUT_FAILURE = "SIGNOUT_FAILURE";
//SIGN UP
export const SIGNUP_BEGINS = "SIGNUP_BEGINS";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";
//EMAIL CONFIRMATION
export const EMAIL_CONFIRM_BEGINS = "EMAIL_CONFIRM_BEGINS";
export const EMAIL_CONFIRM_SUCCESS = "EMAIL_CONFIRM_SUCCESS";
export const EMAIL_CONFIRM_FAILURE = "EMAIL_CONFIRM_FAILURE";