//TICKET NUMBER ADDED
export const TICKET_UPDATE_BEGINS = "TICKET_UPDATE_BEGINS";
export const TICKET_UPDATE_SUCCESS = "TICKET_UPDATE_SUCCESS";
export const TICKET_UPDATE_FAILURE = "TICKET_UPDATE_FAILURE";
// SEND TICEKT TO SERVER
export const TICKET_CREATE_BEGINS = "TICKET_CREATE_BEGINS";
export const TICKET_CREATE_SUCCESS = "TICKET_CREATE_SUCCESS";
export const TICKET_CREATE_FAILURE = "TICKET_CREATE_FAILURE";
// GET TICEKTS FROM SERVER
export const TICKET_RESET = "TICKET_RESET";
// GET TICEKTS FROM SERVER
export const TICKET_GET_BEGINS = "TICKET_GET_BEGINS";
export const TICKET_GET_SUCCESS = "TICKET_GET_SUCCESS";
export const TICKET_GET_FAILURE = "TICKET_GET_FAILURE";