//TICKET NUMBER ADDED
export const TICKET_UPDATE_BEGINS = "TICKET_UPDATE_BEGINS";
export const TICKET_UPDATE_SUCCESS = "TICKET_UPDATE_SUCCESS";
export const TICKET_UPDATE_FAILURE = "TICKET_UPDATE_FAILURE";

